export const Orentation = {
  POTRAIT: "POTRAIT",
  LANDSCAPE: "LANDSCAPE",
};

export const DashboardDocs = [
  {
    key: "deck",
    type: "url",
    required: true,
    description: "",
    title: "Pitch Deck",
  },
  {
    key: "mission",
    type: "string",
    required: true,
    title: "Update your company mission",
    description:
      "This is what your company's purpose for being is. What does your company stand for?",
  },
  {
    key: "vision",
    type: "string",
    required: true,
    title: "Update your company vision",
    description:
      "This articulates what your company would like to achieve.  Where do you see your company in the future?",
  },
  {
    key: "shortDescription",
    type: "string",
    required: true,
    title: "Describe your company in 2 sentences",
    description:
      "It’s important to be able to describe your company in 2 sentences, ",
  },
  {
    key: "longDescription",
    type: "string",
    required: true,
    title: "Describe your company in 2-3 paragraphs",
    description: "This is an in-depth description of your company.",
  },
  {
    key: "emailCompany",
    type: "string",
    required: true,
    title: "Provide customers with a support email",
    description:
      "This is the primary email that customers, investors, and supporters can use to reach your company.",
  },
  {
    key: "problem",
    type: "string",
    required: true,
    description:
      "This is your why. We need a strong problem identity and solution that you think will solve this problem.",
    title: "Fill out problem statements",
  },
  {
    key: "factSheet",
    type: "url",
    required: true,
    description: "",
    title: "Fact Sheet",
  },
  {
    key: "solution",
    type: "url",
    required: false,
    description: "",
    title: "Solution",
  },
  {
    key: "customerPipeline",
    type: "url",
    required: true,
    description: "",
    title: "Customer Pipeline",
  },
  {
    key: "competitorAnalysis",
    type: "url",
    required: false,
    description: "",
    title: "Competitor Analysis",
  },
  {
    key: "teamBio",
    type: "url",
    required: true,
    description: "",
    title: "Team Bios",
  },
  {
    key: "milestoneSch",
    type: "url",
    required: true,
    description: "",
    title: "Milestone Schedule",
  },
  {
    key: "PDP",
    type: "url",
    required: false,
    description: "",
    title: "PDP",
  },
  {
    key: "GTM",
    type: "url",
    required: false,
    description: "",
    title: "GTM",
  },
  {
    key: "custCallSheet",
    type: "url",
    required: false,
    description: "",
    title: "Customer Call Sheet",
  },
  {
    key: "testimonial",
    type: "url",
    required: true,
    description: "",
    title: "Testimonials",
  },
  {
    key: "startPartnerships",
    type: "url",
    required: false,
    description: "",
    title: "Start Partnerships",
  },
  {
    key: "advisorList",
    type: "url",
    required: false,
    description: "",
    title: "Advisor List",
  },
  {
    key: "finProjection",
    type: "url",
    required: true,
    description: "",
    title: "Final Projections",
  },
  {
    key: "proforma",
    type: "url",
    required: true,
    description: "",
    title: "Pro forma Statement",
  },
  {
    key: "pitch",
    type: "url",
    required: true,
    description: "",
    title: "2-minute pitch video",
  },
  {
    key: "keyHires",
    type: "url",
    required: true,
    description: "",
    title: "Key Hires",
  },
  {
    key: "marketAnalysis",
    type: "url",
    required: true,
    description: "",
    title: "Market Analysis",
  },
  {
    key: "balanceSheet",
    type: "url",
    required: true,
    description: "",
    title: "Balance Sheet",
  },
  {
    key: "projectPlan",
    type: "url",
    required: true,
    description: "",
    title: "Project Plan",
  },
  {
    key: "milestoneAch",
    type: "url",
    required: true,
    description: "",
    title: "Milestone Achievements",
  },
  {
    key: "execSummary",
    type: "url",
    required: true,
    description: "",
    title: "Executive Summary",
  },
];
